name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/news-analysis-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

    deploy-to-local:
    name: Deploy to Local Windows Machine
    needs: build-and-push-docker-image
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Login to Docker Hub
        shell: powershell
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull latest image
        shell: powershell
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/news-analysis-api:latest

      - name: Stop existing container
        shell: powershell
        continue-on-error: true
        run: docker stop news-analysis-api

      - name: Remove existing container
        shell: powershell
        continue-on-error: true
        run: docker rm news-analysis-api

      - name: Run new container
        shell: powershell
        run: docker run -d -p 8000:8000 --name news-analysis-api ${{ secrets.DOCKERHUB_USERNAME }}/news-analysis-api:latest